site_name: Generic Configurations (Basic & Advance)
copyright: 'Copyright &copy; 2020 Siddharth Dashore'

theme:
  logo: 'images/logo.svg'
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  favicon: 'assets/images/favicon.ico'
  features:
    - tabs
  extra_css: 'stylesheets/extra.css'
nav:                 

- Home: 'index.md'
- Docker:
    - Overview: 'content/docker/overview.md'
    - Setup Docker in Linux VM: 'content/docker/Setup_Docker_In_Linux_VM.md'

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
        base_path: docs
  - toc:
      permalink: false
      toc_depth: 4

plugins:
  - search
  - macros
#Variables can be accessed in .md files like this example.
#{{ versions.python }}
#After every change in global constants we need to execute "build.bat" file again to reflect into local debugging setup.

#Content from other .md files can be included like this example. Note that here all path should added w.r.t base path of the existing page. Here in case of index we need to provide from ./content only.
#-   {!./content/common/sample.md!}

extra:
  auther_name: Dash
  versions:
    python: 3.4